# Generated by Django 5.2.11 on 2026-02-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_slots', models.IntegerField(default=50)),
                ('available_slots', models.IntegerField(default=20)),
                ('price_per_hour', models.FloatField(default=20)),
            ],
        ),
    ]
